### ISSUE TITLE
Exclude selected options from multiselect dropdown

### ISSUE THREAD

**Issue by sandino** [yourlabs/django-autocomplete-light#1005]
Hello,

I read in docs:

> Quite often (especially in multiselect) you may want to exclude value which is already selected from autocomplete dropdown. Usually it can be done by forwarding a field by name.

and

> For this special case DAL provides a shortcut named Self().

First, adding `forward=('field_name',)` has no effect for me (`django-autocomplete-light==3.2.10` and `django==1.11.10`), the selected options are still in dropdown list, they're just marked with gray background.

Second, if I try to use shortcut `forward=(forward.Self())` I get error:

> AttributeError: module 'dal.forward' has no attribute 'Self'

**Comment by jihoon796** [comment]
@sandino 

There are several solutions to your problem. It's been 5 months, so I'm assuming you've given up by now, but in case this helps the community:

Regarding this issue: 
> AttributeError: module 'dal.forward' has no attribute 'Self'

This was resolved when I upgraded to ```django-autocomplete-light==3.3.0```

In addition, the ```forward``` argument expects a tuple (which isn't clear from the documentation), so it should really be ```forward=(forward.Self(),)```.

**Comment by sandino** [comment]
>  It's been 5 months, so I'm assuming you've given up by now

Nope, I've been waiting for you answer, seriously :)

But I'm still not able to use this solution until #1029 is fixed. Should I close my (this) issue?

**Comment by jihoon796** [comment]
> the selected options are still in dropdown list, they're just marked with gray background.

Now that I think about it - even with the "fix", it still exhibits this behavior. Adding ```forward=('field_name',)``` does the same for me, which means that might be working as intended after all. 

This may be intentional, because if you click the selected option (with the gray background) again, it de-selects it. I'm not sure entirely though.
