### ISSUE TITLE
Widget with required fails to work in most browsers

### ISSUE THREAD

**Issue by marshalc** [yourlabs/django-autocomplete-light#498]
Hi, I'm using 2.2.6 and facing a problem that is either a bug, or I'm doing something very wrong.

Have included an autocomplete field in place of a select widget in a short html5 form, but when it comes to submit the form (after selecting a valid autocomplete option) IE, Firefox, and Chrome all fail to submit because they're saying that one of the fields is incomplete - because the text input has the required="required" attribute. Safari works fine (I suspect because it doesn't apply the inline form validation to widgets that are set to hidden), but Chrome comes back with "An invalid form control with name='donor-perfusion_technician-autocomplete' is not focusable."

The field should be marked as required, so removing that as a field attribute in the form code seems invalid (and would make the validation fail). From looking at the autocomplete codebase briefly, it would seem that in widgets.py, either build_attrs() or build_widget_attrs() should be stripping out the required attribute and putting it on the hidden select rather than the text input.

Can anyone else confirm this please?

**Comment by jpic** [comment]
Can you reproduce this on the online demo project hosted by pythonanywhere
?​

**Comment by marshalc** [comment]
I would love to be able to, but none of the forms on http://jpic.pythonanywhere.com/ contain a required autocomplete field. Everyone of them is optional.

**Comment by jonashaag** [comment]
I have the same issue here. The problem is that as soon as you make enough selections, the `<input type=text name="id_yourfield-autocomplete" ...>` is hidden, even though it has an empty `value` and `required="required"` set. So what happens when you submit the form is that the browser tries to do form validation but can't show the _Please fill out this field_ error messages because the element is hidden.

I'm not sure if there is some graceful fallback if Javascript is disabled in the browser? If so, we should removed the `required` attribute in Javascript. If not, we should make sure we never emit the `required="required"` tag in the Python code.

**Comment by jonashaag** [comment]
Update: The `required` HTML attribute is not being set by Django or autocomplete-light, but by some 3rd party code (`django-bootstrap3` in my case). So it's not a bug in autocomplete-light. At most it's an oversight that we may fix as follows:

* Add a warning about the `required` attribute in the code if we see it
* Always remove the `required` attribute from fields that may be hidden
* Raise an error if we see a `required` attribute

**Comment by jpic** [comment]
Is it possible to reproduce this in the test project ? See faq for details
if needed.
It's a bit tricky indeed but we might find a nice solution if mode of us
can "touch" the issue ;)

**Comment by jonashaag** [comment]
```py
from __future__ import unicode_literals

from django.core import urlresolvers
from django.db import models
from django.utils.encoding import python_2_unicode_compatible


class RequiredFK(models.ForeignKey):
    def formfield(self, **kwargs):
        field = super(RequiredFK, self).formfield(**kwargs)
        field.widget.attrs['required'] = True
        return field


@python_2_unicode_compatible
class NonAdminAddAnotherModel(models.Model):
    name = models.CharField(max_length=100)
    widgets = models.ManyToManyField('self', blank=True)
    fk = RequiredFK('self')

    def get_absolute_url(self):
        return urlresolvers.reverse(
            'non_admin_add_another_model_update', args=(self.pk,))

    def __str__(self):
        return self.name
```

This should do the trick

**Comment by ikcam** [comment]
Found another approach, in a JS file put this:

```javascript
jQuery(document).ready(function($){
	$(document).bind('selectChoice', function(e, choice, autocomplete){
		if( autocomplete.input.attr('required') !== undefined ){
			autocomplete.input.removeAttr('required')
			autocomplete.input.attr('data-required', 'required')
		}
	})

	$(document).bind('widgetDeselectChoice', function(e, choice, autocomplete){
		if( autocomplete.input.attr('data-required') !== undefined ){
			autocomplete.input.removeAttr('data-required')
			autocomplete.input.attr('required', 'required')
		}
	})
})
```

Hide the required required attribute as soon as you select a choice and save the attribute un a data-required attribute to later on if the user deselect the choice the field will still be required.

**Comment by jpic** [comment]
Probably our python widget should transfer required from the select attrs to the input attrs, would that work ?

**Comment by ikcam** [comment]
It already is on the input, i guess you mean transfer it from the input to
the select field

That's won't work because if you don't put anything there and the field is
required you won't get an alert message from the browser.

**Comment by jpic** [comment]
Fixed by @dsanders11 in https://github.com/yourlabs/jquery-autocomplete-light/pull/17

released in 2.3.0

**Comment by dsanders11** [comment]
:+1:

**Comment by SaeX** [comment]
This issue still exists when using Django 1.10 with DAL 2.3.3. 
When reverting to Django 1.9 (and keeping DAL 2.3.3) however, the issue is gone.

**Comment by jpic** [comment]
Is there any way to reproduce this ?

**Comment by SaeX** [comment]
Yes sir: https://github.com/SaeX/dal-issue-498/

**Comment by jpic** [comment]
Oh, I forgot this was on version 2. As much as I love JAL and all, I just can't maintain it.

> it would seem that in widgets.py, either build_attrs() or build_widget_attrs() should be stripping out the required attribute and putting it on the hidden select rather than the text input.

Did you try that ? Seems like this would work.

**Comment by SaeX** [comment]
Not sure about that, this is too low-level for me I'm afraid.

What I did see is that the "[fix](https://github.com/yourlabs/jquery-autocomplete-light/pull/17)" in 2.3.0 was using JS only. 
Also, previous comments state that this is related to bootstrap; that's not the case since [my example project](https://github.com/SaeX/dal-issue-498/) does not use bootstrap.

That doesn't explain though why this is seen on Django 1.10.x and NOT on Django 1.9.

The delta between page rendering on Django 1.9.9 and Django 1.10.1 is that both `<input id="id_start_date" ...>` and `<input name="code_text-autocomplete" ...>` carry the `required` attribute out of sudden. Why is that?

**Comment by Zenonquest** [comment]
Running into the same problem.  Seems like dal doesn't work with required fields if you want to do client-side validation

**Comment by jpic** [comment]
Upgrade to dal v3 and this should not happen on select2

**Comment by Zenonquest** [comment]
@jpic I'm using dal v3.2.1 and still am getting this issue.

**Comment by jpic** [comment]
I'm sorry @Zenonquest , you might be experiencing a similar issue, but it's not the same, because it's not the same code **at all**, but if you don't want to understand it's fine by me: IDGAF.

Otherwise, if your issue matters for you, please open a new issue with all necessary details, because: it's not the same issue as here. 

I'm a bit sorry these days I sound like a broken record when I'm just trying to maintain this project properly for free, if it continues this way that'll mean I'll just have to take a break.

**Comment by jpic** [comment]
Actually @Zenonquest there's more information you need:

- does your issue happen with pure-select2 and without DAL ? -> then it's a [select2 issue](https://github.com/select2/select2)
- does your issue happen with DAL, but not with select2 alone ? -> then it's a dal issue ;)

Wish you luck ^^
