### ISSUE TITLE
Reverse for 'step-autocomplete' with arguments '()' and keyword arguments '{}' not found. 0 pattern(s) tried: []

### ISSUE THREAD

**Issue by sid9553** [yourlabs/django-autocomplete-light#736]
In the stage where I have to reverse the url in the shell, I get this error. I've spent a day trying to fix it with no luck. Does anyone know how to fix this? And can the fix be added to the docs for anyone else with this issue? 'Ensure that the url can be reversed' is rather vague

**Comment by sid9553** [comment]
Fixed it! had to put the url into my main urls.py not the apps urls.py.

**Comment by unknownArtist** [comment]
i am still getting this.. as i put it in main urls.py .. 

can anybody confirm its working with **python3.5+** ?

**Comment by jpic** [comment]
This error is not related to DAL, it's because Django can't find your url.

Do manage.py shell:

     from django.core.urlresolvers import reverse
     reverse('your-url')

If that doesn't work then your url is not registered properly. See what file corresponds to the ROOT_URLCONF setting, that's the file where you should register your url, either directly, either through include().
