### ISSUE TITLE
Metaclass conflict with autocomplete-light 2.3.3 and six 1.11

### ISSUE THREAD

**Issue by tinycogio** [yourlabs/django-autocomplete-light#914]
When running autcomplete-light 2.3.3 with the latest version of six @ 1.11, you will get the following error.

```
TypeError: Error when calling the metaclass bases
    metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

See https://github.com/benjaminp/six/issues/210. Reading through the comments, it sounds like __metaclass__ should not be specified in combination with `six.with_metaclass`

To work around the issue, we are pinning six to `1.10`

---
Reproduced on both Django 1.9 and 1.11

**Comment by ZhbL** [comment]
+1

**Comment by saxbophone** [comment]
I am also experiencing this issue

**Comment by GabrielDumbrava** [comment]
I also have this issue with Django 1.7, six 1.10 and autocomplete 2.3.3

**Comment by jpic** [comment]
Please, stop "it dosen't work for me neither", at this point the only thing you should care about is are you going to contribute this 1 line deletion patch to fix the issue.

**Comment by saxbophone** [comment]
@jpic Point taken —I think such comments have been made in good faith, as knowing with which versions of Django the issue is appearing could be useful information for a fix. However, based on recent comments it seems likely that the issue exists for all Django versions which autocomplete-light supports.

**Comment by jpic** [comment]
fixed in 2.3.4 please feel free to make a pull request next time this is open bar repository

**Comment by saxbophone** [comment]
@jpic great news, thanks! If I'd have known this was as easy as updating a dependency, I'd have done so myself, but am not familiar enough with the project.

**Comment by hakjoon** [comment]
This doesn’t actually fix the issue, it just pins six to the version that doesn’t warn you about the problem.  Is there expecatation that the 2.x.x branch would keep working with newer packages or has it reached end of life at this point? It is described a stable but I don’t know if that means bugs like this should get fixed. Happy to attempt a PR if this version is still maintained.

**Comment by jpic** [comment]
I still have v2 in two products, but we can schedule it to end of life because we have a DRY pattern for v3 since #995, we just need to expand it a bit more to all widgets.

Meanwhile, 2.3.6 release fixes the issue for me.

**Comment by hakjoon** [comment]
I’m still running v2 in a couple places as well so this is good news for me as well. 

2.3.6 does indeed address the underlying problem with this issue. Thanks for fixing that.
